scripts/cve_create: Properly clean up if bippy fails
If bippy fails, put the reserved id back as we don't want to waste it,
and print out an error message.

Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

diff --git a/scripts/cve_create b/scripts/cve_create
--- a/scripts/cve_create
+++ b/scripts/cve_create
@@ -116,6 +116,14 @@ echo "${GIT_SHA_FULL}" > "${PUBLISHED_DIR}/${ID}.sha1"
 
 # write the new json and mbox entry out, using bippy
 "${DIR}"/bippy --cve="${ID}" --user="${USER}" --sha="${GIT_SHA_FULL}" --json="${PUBLISHED_DIR}/${ID}.json" --mbox="${PUBLISHED_DIR}/${ID}.mbox"
+result=$?
+if [[ "${result}" != 0 ]]; then
+	# move the id back to the reserved area and delete the .sha1 file
+	mv "${PUBLISHED_DIR}/${ID}" "${RESERVED_DIR}"
+	rm "${PUBLISHED_DIR}/${ID}.sha1"
+	echo "${txtred}Error:${txtrst} bippy failed to create ${txtcyn}${ID}${txtrst} for commit ${txtgrn}${GIT_COMMIT}${txtrst}"
+	exit 1
+fi
 
 # say all is good, and give the id
-echo "${txtcyn}${ID}${txtrst} is now allocated for git commit ${txtgrn}${GIT_COMMIT}${txtrst}"
+echo "${txtcyn}${ID}${txtrst} is now allocated for commit ${txtgrn}${GIT_COMMIT}${txtrst}"
