scripts/cve_update: handle the email changes better
Also make the output one line per id, to condence it, and handle errors
from bippy properly.

Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

diff --git a/scripts/cve_update b/scripts/cve_update
--- a/scripts/cve_update
+++ b/scripts/cve_update
@@ -59,7 +59,7 @@ for id in cve/published/*/*.sha1 ; do
 	cve=$(echo "${id}" | cut -f 1 -d '.' | cut -f 4 -d '/')
 	root=$(echo "${id}" | cut -f 1 -d '.')
 	#echo "id=${id} sha=${sha} cve=${cve}"
-	echo "Updating ${txtcyn}${cve}${txtrst}..."
+	echo -n "Updating ${txtcyn}${cve}${txtrst}..."
 
 	# Look to see if we have a "og_vuln" that is provided to us in a
 	# published CVE.  This is used for when we can't determine it on our
@@ -74,32 +74,38 @@ for id in cve/published/*/*.sha1 ; do
 
 	# Create the new json and mbox files
 	"${DIR}"/bippy --cve="${cve}" --sha="${sha}" --json="${tmp_json}" --mbox="${tmp_mbox}" --vulnerable="${vulnerable_sha}"
+	result=$?
+	if [[ "${result}" != 0 ]]; then
+		# bippy failed, so report it and continue on
+		echo "${txtred}Error:${txtrst} bippy failed to create ${txtcyn}${cve}${txtrst} for commit ${txtgrn}${sha}${txtrst}"
+		continue
+	fi
 
 	# see if the json and/or mbox files actually changed, EXCEPT for the bippy-VERSIONINFO string
-	changed=0
-	diff=$(diff -u "${root}.json" "${tmp_json}" | grep -v "${tmp_json}" | grep -v "${root}.json" | grep -v "bippy-" | grep -v "^@@ " | grep "^[+|-]")
+	updated_file=""
+	diff=$(diff -u "${root}.json" "${tmp_json}" | grep -v "${tmp_json}" | grep -v "${root}.json" | grep -v "bippy-" | grep -v "^@@ " | grep "^[+|-]" | grep -v "kernel.org" | grep -v "linuxfoundation.org")
 	#echo "diff json=${diff}"
 	if [[ "${diff}" != "" ]] ; then
 		mv -f "${tmp_json}" "${root}.json"
-		echo "	Updated ${txtblu}${root}.json${txtrst}"
-		changed=1
+		updated_file+="${root}.json"
 	else
 		rm "${tmp_json}"
 		#echo "diff for json was empty"
 	fi
 
-	diff=$(diff -u "${root}.mbox" "${tmp_mbox}" | grep -v "${tmp_mbox}" | grep -v "${root}.mbox" | grep -v "bippy-" | grep -v "^@@ " | grep "^+")
+	diff=$(diff -u "${root}.mbox" "${tmp_mbox}" | grep -v "${tmp_mbox}" | grep -v "${root}.mbox" | grep -v "bippy-" | grep -v "^@@ " | grep "^+" | grep -v "kernel.org" | grep -v "linuxfoundation.org")
 	#echo "diff mbox=${diff}"
 	if [[ "${diff}" != "" ]] ; then
 		mv -f "${tmp_mbox}" "${root}.mbox"
-		echo "	Updated ${txtblu}${root}.mbox${txtrst}"
-		changed=1
+		updated_file+=" ${root}.mbox"
 	else
 		rm "${tmp_mbox}"
 		#echo "diff for mbox was empty"
 	fi
-	if [[ "${changed}" == "0" ]] ; then
+	if [[ "${updated_file}" == "" ]] ; then
 		echo "	${txtgrn}Nothing changed${txtrst}"
+	else
+		echo "	Updated ${txtblu}${updated_file}${txtrst}"
 	fi
 done
 
